- CHANGELOG.md
- examples/nlp/gpt/train_gpt_dpo.py
- examples/nlp/gpt/train_gpt_ppo_actor.py
- examples/nlp/gpt/train_gpt_sft.py
- examples/nlp/gpt/train_reward_model.py
- nemo_aligner/algorithms/dpo.py
- nemo_aligner/algorithms/ppo.py
- nemo_aligner/algorithms/supervised.py
- nemo_aligner/utils/distributed.py
- nemo_aligner/utils/trainer_utils.py
> add timer impl

- CONTRIBUTING.md
This is so that both the "Signed-off-by" message *and* the proper GPG signature are used.
cc @gleibovich-nvidia
> Fix instructions to sign commits

- CHANGELOG.md
- Dockerfile
- README.md
fixes signing issues with #47 and #74
> add stable dockerfile

- nemo_aligner/models/nlp/gpt/megatron_gpt_reward_model.py
- nemo_aligner/utils/train_utils.py
change function name because of NeMo [PR](https://github.com/NVIDIA/NeMo/commit/58a277a526f71cb05d7a496c6cccebf388900cb2)
> fix function name change from nemo

- CHANGELOG.md
- nemo_aligner/algorithms/critic_server_trainer.py
The problem was that PyTriton expects all outputs to have the same batch size, while the critic was returning a dummy length-1 tensor for rewards. It is cleaner to just not reeturn rewards at all.
@gshennvm should we add this setup to CI?
> Fix crash when using a separate reward model server in PPO

- CHANGELOG.md
- nemo_aligner/algorithms/ppo.py
Add extra call to `clear_memory()` to fix OOM when sending critic data
For several weeks now I've been regularly running into
```
File "/lustre/fs6/portfolios/llmservice/users/odelalleau/data/exp/rlhf/39-4c_ppo-43b-mb-hh-rm39-2-rkl1e-2-lr2e-7/NeMo-Aligner/examples/nlp/gpt/train_gpt_ppo_actor.py", line 175, in main
ppo_trainer.fit()
File "/lustre/fsw/portfolios/llmservice/users/odelalleau/data/exp/rlhf/39-4c_ppo-43b-mb-hh-rm39-2-rkl1e-2-lr2e-7/NeMo-Aligner/nemo_aligner/algorithms/ppo.py", line 388, in fit
self.rm_critic.train(ppo_rollout_data)
File "/lustre/fsw/portfolios/llmservice/users/odelalleau/data/exp/rlhf/39-4c_ppo-43b-mb-hh-rm39-2-rkl1e-2-lr2e-7/NeMo-Aligner/nemo_aligner/models/nlp/gpt/reward_critic_clients.py", line 150, in train
send_data["tokens"] = …
```
> Add extra call to `clear_memory()` to fix OOM when sending critic data

- examples/nlp/gpt/train_gpt_dpo.py
- examples/nlp/gpt/train_gpt_ppo_actor.py
- examples/nlp/gpt/train_gpt_sft.py
- examples/nlp/gpt/train_reward_model.py
- nemo_aligner/data/nlp/builders.py
Fixes issue #107 by allowing having `build_dataloader` support both deterministic and random samplers, and revert PPO `val_dataloader` to be a deterministic one, thus allowing tracking the same batch during a PPO run. 
The same issue seems to also be present with DPO. Is the expected behavior same as with PPO and we'd like to use a deterministic batch sampler with DPO as well?
> Fix random sampler keeping state with validation runs

- CHANGELOG.md
- nemo_aligner/algorithms/spin.py
Fixes an error in SPIN if you get samples where the prompt length exceeds the model's max seq length minus your generation.max_length
> SPIN bug fix for prompt lengths being greater than generation.max_length

- examples/nlp/gpt/conf/gpt_sft.yaml
Change default value of `drop_last` to True for SFT validation set (since False is not supported anyway and systematically crashes).
- No changelog update since nobody could run `drop_last=False` anyway
> Change default value of `drop_last` to True for SFT validation set

- CHANGELOG.md
- nemo_aligner/models/nlp/gpt/gpt_reward_model.py
- nemo_aligner/models/nlp/gpt/megatron_gpt_reward_model.py
Add moe support for reward model(this allows mixtral to be used). Note that by default the other models inherit MegatronGPTModel which has MoE support already. We need to add this because we use a modified GPTModel for the RM
> add moe support in reward model

- CHANGELOG.md
- nemo_aligner/models/nlp/gpt/gpt_sft_model.py
This fixes an issue where our new `generate()` method for SFT models didn't support string inputs at all. But when `compute_logprob=True`, we don't actually care about the padding & extra `predictions` key added by this method, so we can support string inputs easily by simply re-using the parent class' `generate()`.
This is useful e.g. for benchmarking purpose (this is how I tested it -- with the MMLU benchmark).
> Allow computing logprobs of SFT model on input strings

- examples/nlp/gpt/conf/gpt_ppo_actor.yaml
- nemo_aligner/algorithms/critic_server_trainer.py
- nemo_aligner/models/nlp/gpt/megatron_gpt_ppo_actor.py
- nemo_aligner/utils/trt_llm.py
> trtllm0.9 changes

- CHANGELOG.md
- examples/nlp/gpt/conf/gpt_dpo.yaml
- examples/nlp/gpt/conf/gpt_sft.yaml
- examples/nlp/gpt/conf/gpt_spin.yaml
- nemo_aligner/algorithms/dpo.py
- nemo_aligner/algorithms/spin.py
- nemo_aligner/algorithms/supervised.py
- nemo_aligner/utils/trainer_utils.py
Adds support for float values for `val_check_interval` for SFT. It also adds support for floats/ints for `limit_train_batches` to SFT and DPO, as per the usage in [PTL](https://lightning.ai/docs/pytorch/stable/common/trainer.html#limit-train-batches)
This was requested by @Kipok 
```yaml
val_check_interval = 0.25   # means you will run validation 4 times per epoch
val_check_interval = 100    # means you will run validation every 100 steps of training
limit_train_batches = 0.5   # you will only use 50% of your training data per epoch
limit_train_batches = 100  # you will only consume 100 steps of your train dataloader per epoch
```
All …
> Added support for float values for val_check_interval to SFT

- CHANGELOG.md
- nemo_aligner/algorithms/spin.py
Adds wandb logging of avg generation length for SPIN as well as a table showing sample generated responses for their corresponding prompts.
> SPIN: Added logging for avg generation length and generated responses as wandb table

- nemo_aligner/models/nlp/gpt/gpt_sft_model.py
The type support for inputs now matches MegatronGPTModel which was important to use megatron_gpt_eval.py
```python
```
> Add feat to allow GPTSFTModel.generate from str inputs

- nemo_aligner/algorithms/ppo.py
> Avoids crash in PPOTrainer if using adafactor w/o learning rate

- nemo_aligner/utils/trainer_utils.py
Fixed minor float check bug in compute_num_steps_per_epoch
```python
```
> Fixed minor float check bug in compute_num_steps_per_epoch

- CHANGELOG.md
- examples/nlp/gpt/conf/gpt_dpo.yaml
- nemo_aligner/models/nlp/gpt/megatron_gpt_dpo_model.py
This PR fixes the log probs mismatch issue (https://github.com/NVIDIA/NeMo-Aligner/issues/227) between policy and reference policy in DPO/RPO/variants.
This PR solves this issue with two changes:
* Refactor the code to compute `reference policy log probs` so that it is exactly the same as the code to compute `policy log probs`. This removes any issue related to MBS, GBS, DP, TP mismatches.
* ~~Fix [the bug here](https://github.com/NVIDIA/NeMo-Aligner/blob/8d8ef38bc7b190d9a3d0b5face76147b9e0ae863/nemo_aligner/models/nlp/gpt/megatron_gpt_dpo_model.py#L345) which messes up the `reference policy log probs` with their corresponding tokens.~~
With this change, the reference policy log probs match the policy log probs exactly at the first iteration.
> fix log probs mismatch

- README.md
fix broken links, unfortunately they no longer host our llama2 models
> fix HF links in readme

- nemo_aligner/models/nlp/gpt/megatron_gpt_dpo_model.py
Fix the `num_microbatches` in `forward_backward_func` when using customized `log_prob_forward_micro_batch_size`.
* When using the default `log_prob_forward_mbs = 2 * micro_batch_size`, this does not affect `num_microbatches`.
* When using a customized `log_prob_forward_mbs`, the `num_microbatches` should be changed accordingly.
```python
```
> Fix num_micro_batches when using forward_mbs

- CHANGELOG.md
- docs/user-guide/sft.rst
- nemo_aligner/data/nlp/builders.py
Adds sequence packing for `SFTPackedDataset`. Thanks @RadhaGulhane13 for the contribution!
Original usage example from https://github.com/NVIDIA/NeMo-Aligner/pull/259:
The following documentation can be referred to for dataset preparation and adjusting training configurations : https://github.com/NVIDIA/NeMo/blob/main/docs/source/features/throughput_optimizations.rst#how-to-run-sftpeft-with-packed-sequence
```
TRAIN_DATA_PATH="<train_dataset_path>/packed_32768_seed0.npy"
VALID_DATA_PATH="<val_dataset_path>/packed_32768_seed0.npy"
python <path_to_Nemo-Aligner>/examples/nlp/gpt/train_gpt_sft.py \
trainer.precision=bf16 \
trainer.num_nodes=1 \
trainer.devices=8 \
trainer.sft.max_steps=-1 …
```
> Add sequence packing support for SFTPackedDataset

- .github/workflows/cicd-main.yml
Current rules disallow running on main, as the label `Run CICD` aint there
```python
```
> ci: Allow running on main

- CHANGELOG.md
- Dockerfile
> build: Improve caching

- .github/workflows/_build_container.yml
- .github/workflows/cicd-main.yml
- .github/workflows/release.yaml
- MANIFEST.in
Implements a manual `workflow_dispatch`  that allows us to build, test, and publish a PyPi wheel as well as create GH release (tag).
It is secured by a GH environment that runs on `main` (protected) only by a PyPi token that is resolved in this environment only. Put different: If one tries to use this token on a branch other than `main` it will be empty. So to make use of this token, they need to be able to merge their script into main, which of course only works by review.
The release page will be populated by the `CHANGELOG.md` file (awesome that you already have that!!). I extract the section from (incl) to (excl) `## ...` blocks as the description of the release page.  
* You can …
> ci: Release automation

- Dockerfile
- nemo_aligner/models/nlp/gpt/megatron_gpt_ppo_actor.py
- nemo_aligner/utils/trt_llm.py
This PR contains two changes:
1. Change to the dockerfile to allow two types of builds
```sh
docker buildx build -t aligner:latest .
docker buildx build --target=aligner-bump \
--build-arg=BASE_IMAGE=nvcr.io/nvidia/nemo:24.07 \
--build-arg=ALIGNER_COMMIT=dev \
-t aligner:latest .
```
2. Moves the error message when either (a) TRTLLM isn't installed (b) doesn't have v10 refit functionality into GenerateGPTLLM and have the message point to this new dockerfile
```python
```
> feat: update dockerfile to allow incremental builds and change TRTLLM error to point to dockerfile

- nemo_aligner/utils/trt_llm.py
[🤖]: Hi @terrykong 👋,<br><br>we've cherry picked #288 into `r0.5.0` for you! 🚀<br><br>Please review and approve this cherry pick by your convenience\!
> Cherry pick `fix: pad_id=None in tokenizer no longer errors for TRTLLM generation (288)` into `r0.5.0`

- Dockerfile
Fixes the incremental build which wasn't bumping aligner
```sh
docker buildx build --build-arg=BASE_IMAGE=nvcr.io/nvidia/nemo:24.07 --target=aligner-bump -t aligner:latest https://github.com/NVIDIA/NeMo-Aligner.git#tk/0.5/dockerfile-fix
```
```python
```
> fix: Dockerfile now correctly updates aligner in incremental aligner-bump target

- examples/nlp/gpt/conf/inference_rm.yaml
> fix: serve_reward_model.py no longer errors if pretrained GBS indivisible by parallel state

- examples/nlp/gpt/conf/inference_rm.yaml
[🤖]: Hi @terrykong 👋,<br><br>we've cherry picked #333 into `r0.5.0` for you! 🚀<br><br>Please review and approve this cherry pick by your convenience\!
> Cherry pick `fix: serve_reward_model.py no longer errors if pretrained GBS indivisible by parallel state (333)` into `r0.5.0`

- docs/user-guide/dpo.rst
Adds a note to the DPO tutorial that train/valid jsonl files must have at least GBS number of samples each.
```python
```
> docs: Added note about GBS and jsonl samples to DPO tutorial

- Dockerfile
Reverts NVIDIA/NeMo-Aligner#358 since the Dockerfile has largely changed in `dev`. So this change isn't needed and creates a conflict
> revert: "build: use cached trtllm build when updating aligner tag"

- tests/functional/run_all.sh
Make it easier for developers to run all the functional tests without peeking at the github action workflow file
* https://github.com/NVIDIA/NeMo-Aligner/pull/386
* https://github.com/NVIDIA/NeMo-Aligner/pull/387
* https://github.com/NVIDIA/NeMo-Aligner/pull/388
* https://github.com/NVIDIA/NeMo-Aligner/pull/380
```python
```
> feat: adds helper script for running & summarizing functional tests

- nemo_aligner/utils/train_script_utils.py
Add reinforce optimization step to retrieve_custom_trainer_state_dict, which allows for training reinforce with multiple jobs.
- [ Y] Make sure you read and followed [Contributor guidelines](/CONTRIBUTING.md)
- [ N] Did you write any new necessary tests?
- [ N] Did you add or update any necessary documentation? Make sure to also update the [NeMo Framework User Guide](https://docs.nvidia.com/nemo-framework/user-guide/latest/index.html) which contains the tutorials
> fix: correct REINFORCE to resume training

- Dockerfile
- examples/nlp/gpt/serve_reward_model.py
- nemo_aligner/models/nlp/gpt/gpt_sft_model.py
- nemo_aligner/models/nlp/gpt/megatron_gpt_critic.py
- nemo_aligner/models/nlp/gpt/megatron_gpt_dpo_model.py
- nemo_aligner/models/nlp/gpt/megatron_gpt_kto_model.py
- nemo_aligner/models/nlp/gpt/megatron_gpt_ppo_actor.py
- nemo_aligner/models/nlp/gpt/megatron_gpt_regression_reward_model.py
- nemo_aligner/models/nlp/gpt/megatron_gpt_reward_model.py
- nemo_aligner/models/nlp/gpt/megatron_gpt_rs_actor.py
- nemo_aligner/models/nlp/gpt/megatron_gpt_spin_model.py
- nemo_aligner/utils/train_script_utils.py
- setup/requirements.txt
- tests/conftest.py
This reverts commit 32670609bef82532647a327fec865afa68a8152f, reversing changes made to c69b872951d859d97faec98668aae69d71a8352b.
Pushing the update branch on #413 actually created a merge commit on main, which should not have been allowed. 
```python
```
> revert: "Merge branch 'dev' into main"

- .github/workflows/_run_test.yml
- .github/workflows/cicd-main.yml
- Dockerfile
- nemo_aligner/utils/utils.py
- tests/functional/dpo.sh
- tests/functional/test_cases/dpo-llama3
- tests/functional/test_cases/e2e-nemo2
Depends on https://github.com/NVIDIA/NeMo/pull/11452
```python
```
> feat: Add support for loading NeMo 2.0 checkpoints

- .github/workflows/release-freeze.yml
- .github/workflows/release.yaml
> ci: Bump release worflow

- .github/workflows/cicd-main.yml
* Adds a final check so that we can handle dynamic status checks
* Adds option to skip CI by label `Skip CICD`
* Adds auto-skip for changes inside `docs/` only
```python
```
> ci: Add final status check

- docs/user-guide/dpo.rst
> docs: add llama download command

- .github/workflows/cicd-main.yml
`${{ github.event.pull_request.head.sha || github.sha }}` runs - for PRs - on the source branch instead of merge commit. This is almost never really good, and the cause of the intransparent failure of https://github.com/NVIDIA/NeMo-Aligner/actions/runs/12419036746
```python
```
> ci: Use `github.sha` for build

- .github/workflows/cicd-main.yml
Getting a change_set obviously doesn't work `on: push`, so we have to disable that action there (more precisely: make it only runs `on: pull_request`).
And also we want to make sure that the label-constraint is only effective if event_type is pull_request, otherwise push or manual_dispatch won't work anymore.
```python
```
> ci: Run on `main`

- .github/workflows/cicd-main.yml
- .github/workflows/release-freeze.yml
- .github/workflows/release.yaml
- docs/user-guide/dpo.rst
- docs/user-guide/reinforce.rst
- docs/user-guide/rlhf.rst
> chore: sync main to dev

- nemo_aligner/package_info.py
> fix: Generate version number

- nemo_aligner/package_info.py
Instead of `0.6.0rc0.dev` we were creating this `0.6.0rc0.d.e.v.0`
```python
```
> fix: dev segment in version specifier joined properly

- tests/conftest.py
This fix was only in `dev`, so cherry-picking it into `main`
```python
```
> fix: session start fixture correctly handles being launched by mpirun

- Dockerfile
- setup/requirements.txt
> fix: pynvml is pinned when using TRTLLM v13 due to breaking change in 12.0.0

- Dockerfile
> fix: Add triton downgrade as long as we're on pytorch 24.07

- docs/user-guide/index.rst
- docs/user-guide/reinforce.rst
> docs: fix linking of reinforce from index and add it to support table

- .github/workflows/cicd-main.yml
> ci: Properly enable merge-queue

- CHANGELOG.md
- examples/nlp/gpt/conf/training_rm.yaml
- examples/nlp/gpt/train_reward_model.py
- nemo_aligner/algorithms/supervised.py
- nemo_aligner/data/nlp/builders.py
This PR enables reward model training with multiple validation datasets.
In addition to a main validation dataset, you can optionally specify additional validation datasets in data_prefix. The additional keys should start with "validation". Metrics are computed for each validation dataset and logged in separate wandb tabs.
Before:
```python
python ${NEMO_ALIGNER_PATH}/examples/nlp/gpt/train_reward_model.py \
...
++model.data.data_prefix="{train:[${TRAIN_DATA}],validation:[${VAL_DATA}],test:[${TEST_DATA}]}" \
...
```
After:
```python
python ${NEMO_ALIGNER_PATH}/examples/nlp/gpt/train_reward_model.py \
...
++model.data.data_prefix="{train:[${TRAIN_DATA}],validation:[${VAL_DATA}],validation_other:[${VAL_OTHER_DATA}],test:[${TEST_DATA}]}" \
...
```
> feat: enable reward model training with multiple validation datasets

- CHANGELOG.md
- examples/nlp/gpt/train_reward_model.py
- nemo_aligner/algorithms/supervised.py
- nemo_aligner/data/nlp/builders.py
- nemo_aligner/models/nlp/gpt/megatron_gpt_reward_model.py
This PR enables reward model training with validation_drop_last =False.
```python
python ${NEMO_ALIGNER_PATH}/examples/nlp/gpt/train_reward_model.py \
...
++model.data.validation_drop_last=False \
...
```
> feat: enable reward model training without dropping the last validation batch

- examples/nlp/gpt/train_reward_model.py
- nemo_aligner/algorithms/supervised.py
This PR makes minor adjustments to the reward model training related to the usage of `validation_drop_last`.
> feat: minor adjustments to the reward model training
