- docs/user-guide/RLHF.rst
fixing PPO hparams link in doc
> fix ppo hparams link

- README.md
> add rlhf model link

- examples/nlp/gpt/train_gpt_sft.py
simple bug fix. the `sft_trainer` should be `trainer.sft`
> fix SFT config bug

- .github/workflows/sync_branch.yaml
- CONTRIBUTING.md
> add dev github action, and update contributing guide

- docs/user-guide/RLHF.rst
fix confusing naming for which dolly file to use
> fix dolly name to use

- Dockerfile
logic of dockerfile does not change but need to change the ALIGNER_COMMIT arg so it's easier to run on the nemo-ci
> change dockerfile for ci

- CHANGELOG.md
- examples/nlp/gpt/conf/gpt_dpo.yaml
- examples/nlp/gpt/conf/gpt_ppo_actor.yaml
- examples/nlp/gpt/conf/gpt_sft.yaml
- examples/nlp/gpt/conf/training_rm.yaml
- nemo_aligner/algorithms/dpo.py
- nemo_aligner/algorithms/ppo.py
- nemo_aligner/algorithms/supervised.py
- nemo_aligner/data/nlp/builders.py
- nemo_aligner/data/nlp/datasets.py
- nemo_aligner/data/nlp/samplers.py
- nemo_aligner/utils/trainer_utils.py
Allows training with max_epochs > 1
```python
```
> Multi-Epoch Training

- nemo_aligner/models/nlp/gpt/megatron_gpt_reward_model.py
upgrade to a newer nemo version, which moved the function and changed it to a dictionary
> moving _str_to_dtype

- nemo_aligner/models/nlp/gpt/megatron_gpt_reward_model.py
whoops, didn't notice the public function somehow.
> str to dtype should use the function

- CHANGELOG.md
- Dockerfile
- examples/nlp/gpt/conf/gpt_sft.yaml
- examples/nlp/gpt/train_gpt_sft.py
- nemo_aligner/models/nlp/gpt/gpt_sft_model.py
- nemo_aligner/utils/train_script_utils.py
- nemo_aligner/utils/utils.py
Add LoRA support for SFT/SteerLM
Only support DP and TP
Have to change Dockerfile to cherry pick a new commit in NeMo to support O2
```python
```
> Lora for SFT/SteerLM

- nemo_aligner/utils/utils.py
fix a bug when loading nemo file
```python
```
> load_from_nemo bug fix

- README.md
Adding links to recently published SteerLM and RLHF reward models based on llama2-13B
> Adding links to published reward models

- nemo_aligner/models/nlp/gpt/megatron_gpt_critic.py
free speedup on critic by doing mask construction on GPU
```python
```
> calling .cuda on tokens before mask construction

- CHANGELOG.md
- nemo_aligner/algorithms/dpo.py
> fix dpo val check interval

- docs/user-guide/DPO.rst
- docs/user-guide/RLHF.rst
- docs/user-guide/SFT.rst
- docs/user-guide/SteerLM.rst
- docs/user-guide/index.rst
Updating Section to fit NeMo Framework User Guide
```python
```
> Updating Section to fit NeMo Framework User Guide

- docs/user-guide/SFT.rst
update docs to link to conversion script
> update docs to link to conversion scripts

- docs/user-guide/DPO.rst
- docs/user-guide/SFT.rst
- docs/user-guide/SPIN.rst
- docs/user-guide/SteerLM.rst
> rename checkpoint convert scripts

- nemo_aligner/algorithms/dpo.py
- nemo_aligner/models/nlp/gpt/megatron_gpt_dpo_model.py
Streamlines the augment_dataloader code in DPO making it less messy. There is no change to functionality, this is just a code cleanup.
> Streamlines the augment_dataloader method in DPO

- CHANGELOG.md
- Dockerfile
- examples/nlp/gpt/conf/gpt_sft.yaml
Enable LoRA on all layers (TP,PP,DP,SP)
```python
```
> Enable LoRA on all layers

- CHANGELOG.md
- nemo_aligner/models/nlp/gpt/megatron_gpt_dpo_model.py
fix crash when MBS > 1 in DPO
Fixes #153
> fix DPO mbs > 1 bug

- docs/user-guide/RLHF.rst
fix confusion on checkpoint to use for RLHF
> fix confusion on checkpoint to use

- CHANGELOG.md
- examples/nlp/gpt/conf/gpt_ppo_actor.yaml
- examples/nlp/gpt/train_gpt_ppo_actor.py
- nemo_aligner/models/nlp/gpt/megatron_gpt_ppo_actor.py
Enable LoRA for PPO actor
```python
```
> Enable LoRA for PPO actor

- CHANGELOG.md
- docs/user-guide/SFT.rst
- examples/nlp/gpt/conf/gpt_sft.yaml
- examples/nlp/gpt/conf/gpt_spin.yaml
make the dataset max seq length consistent with the model
> pin the seq length of dataset to the model

- Dockerfile
remove the `rm -rf` so people can see git info
> edit dockerfile

- examples/mm/stable_diffusion/conf/draftp_sd.yaml
> fix sd config

- README.md
Adds the missing SPIN section to to README.md
> Added SPIN section to readme

- docs/user-guide/SFT.rst
- docs/user-guide/SteerLM.rst
fix docs where save_interval < val_interval
> fix save interval in docs

- nemo_aligner/package_info.py
> change dev version

- requirements.txt
newest nemo container deletes jsonlines dependency, adding it back into aligner
> add jsonlines

- docs/user-guide/RLHF.rst
> Small improvements in RM docs

- nemo_aligner/algorithms/critic_server_trainer.py
- nemo_aligner/algorithms/ppo.py
- nemo_aligner/data/nlp/builders.py
> Ensure critic server does not squeeze out a singleton batch dim

- nemo_aligner/models/nlp/gpt/gpt_reward_model.py
fix issue when reward model is trained with 24.01 but loaded with 24.05
> add fix for missing extra state in rm

- examples/nlp/gpt/conf/gpt_spin.yaml
- nemo_aligner/algorithms/spin.py
- nemo_aligner/models/nlp/gpt/megatron_gpt_ppo_actor.py
- nemo_aligner/utils/trt_llm.py
> pull changes from degert/spin-trt-beta

- examples/nlp/gpt/train_gpt_ppo_actor.py
- nemo_aligner/servers/http_communicator.py
> Communicator hang fix in the actor loop

- CHANGELOG.md
- docs/user-guide/dpo.rst
- examples/nlp/gpt/conf/gpt_dpo.yaml
- nemo_aligner/algorithms/dpo.py
- nemo_aligner/data/nlp/datasets.py
- nemo_aligner/models/nlp/gpt/megatron_gpt_dpo_model.py
Implement the reward aware preference optimization algorithms.
```python
```
- [x ] Make sure you read and followed [Contributor guidelines](/CONTRIBUTING.md)
> Implement the reward aware preference optimization algorithms.

- nemo_aligner/algorithms/spin.py
- nemo_aligner/models/nlp/gpt/megatron_gpt_ppo_actor.py
- nemo_aligner/utils/trt_llm.py
> Raise exceptions if using trtllm and use_Greedy in sampling params is set but temperature/topk are not correct for greedy

- docs/user-guide/sft.rst
same as #238 except to trtllm branch instead of rc branch
> Update the hash of the conversion script to include TE fix for mcore conversion

- docs/user-guide/sft.rst
> fix model path sft

- CHANGELOG.md
- nemo_aligner/models/mm/stable_diffusion/megatron_sd_draftp_model.py
- nemo_aligner/models/mm/stable_diffusion/megatron_sdxl_draftp_model.py
- nemo_aligner/models/nlp/gpt/gpt_sft_model.py
- nemo_aligner/models/nlp/gpt/megatron_gpt_critic.py
- nemo_aligner/models/nlp/gpt/megatron_gpt_dpo_model.py
- nemo_aligner/models/nlp/gpt/megatron_gpt_ppo_actor.py
- nemo_aligner/models/nlp/gpt/megatron_gpt_regression_reward_model.py
- nemo_aligner/models/nlp/gpt/megatron_gpt_reward_model.py
- nemo_aligner/models/nlp/gpt/megatron_gpt_spin_model.py
- nemo_aligner/utils/train_utils.py
- nemo_aligner/utils/utils.py
> Updates microbatch APIs to use megatron's instead of apex's

- requirements.txt
> 0.4 mcore constraint

- requirements.txt
> Updates requirements to reflect necessary mcore version (>=0.8)

- README.md
> Point the TRTLLM documentation to Nemo docs

- CHANGELOG.md
- docs/user-guide/sft.rst
- nemo_aligner/data/nlp/builders.py
> [TEST] sequence packing

- README.md
> add comments about rlhf on readme

- docs/user-guide/rlhf.rst
> Add 405B numbers to readme

- nemo_aligner/__init__.py
These imports were dangling. By putting them into `__all__` we expose them properly
```python
```
> style(fix): Unused imports

- CHANGELOG.md
- docs/user-guide/draftp.rst
- examples/mm/stable_diffusion/anneal_sdxl.py
- examples/nlp/data/kto/preprocess_anthropichh_data.py
- examples/nlp/gpt/conf/gpt_kto.yaml
- examples/nlp/gpt/train_gpt_kto.py
- nemo_aligner/__init__.py
- nemo_aligner/algorithms/kto.py
- nemo_aligner/data/nlp/builders.py
- nemo_aligner/data/nlp/datasets.py
- nemo_aligner/models/mm/stable_diffusion/megatron_sd_draftp_model.py
- nemo_aligner/models/mm/stable_diffusion/megatron_sdxl_draftp_model.py
- nemo_aligner/models/nlp/gpt/megatron_gpt_kto_model.py
Implement the [KTO](https://arxiv.org/abs/2402.01306) algorithm 
- [ X] Does the trainer have proper logging?
> Implement KTO

- CHANGELOG.md
- examples/nlp/gpt/conf/gpt_dpo.yaml
- nemo_aligner/models/nlp/gpt/megatron_gpt_dpo_model.py
> fix micro batch size logic in DPO

- MANIFEST.in
- setup.py
> chore: Adjustments for wheel build

- CHANGELOG.md
> docs: Adjust docs to NeMo-FW standard

- nemo_aligner/package_info.py
> chore: Remove pre-release segment

- CHANGELOG.md
> docs: Cherry-pick 0.4.0 changelog

- Dockerfile
> build: Move build arg

- examples/nlp/gpt/train_gpt_sft.py
- examples/nlp/gpt/train_steerlm2.py
- nemo_aligner/utils/utils.py
Add model config override for steerlm2 and sft
```python
```
> Update dist_ckpt_load_strictness for sft and steerlm2

- nemo_aligner/package_info.py
> chore: Fix version number

- .github/workflows/release-freeze.yml
> ci: Add code-freeze automation

- .github/workflows/release-freeze.yml
> ci: Use choice for code-freeze

- .github/workflows/cherry-pick-release-commit.yml
> ci: Add cherry pick automation

- CHANGELOG.md
> fix: update the changelog in preparation for 24.09

- .github/workflows/cherry-pick-release-commit.yml
> ci: Wrap into quotes

- Dockerfile
- nemo_aligner/models/nlp/gpt/megatron_gpt_ppo_actor.py
- nemo_aligner/utils/trt_llm.py
[🤖]: Hi @terrykong 👋,<br><br>we've cherry picked #290 into `r0.5.0` for you! 🚀<br><br>Please review and approve this cherry pick by your convenience\!
> Cherry pick `feat: update dockerfile to allow incremental builds and change TRTLLM error to point to dockerfile (290)` into `r0.5.0`

- CHANGELOG.md
> Cherry pick `fix: update the changelog in preparation for 24.09 (289)` into `r0.5.0`

- Dockerfile
> build: Optimize caching

- Dockerfile
[🤖]: Hi @terrykong 👋,<br><br>we've cherry picked #323 into `r0.5.0` for you! 🚀<br><br>Please review and approve this cherry pick by your convenience\!
> Cherry pick `fix: Dockerfile now correctly updates aligner in incremental aligner-bump target (323)` into `r0.5.0`

- docs/user-guide/dpo.rst
- docs/user-guide/index.rst
> docs: Add sidebar headings for RPO/IPO/DPO with LoRA

- docs/user-guide/dpo.rst
- docs/user-guide/index.rst
[🤖]: Hi @terrykong 👋,<br><br>we've cherry picked #319 into `r0.5.0` for you! 🚀<br><br>Please review and approve this cherry pick by your convenience\!
> Cherry pick `docs: Add sidebar headings for RPO/IPO/DPO with LoRA (319)` into `r0.5.0`

- CHANGELOG.md
- nemo_aligner/utils/train_utils.py
> feat: support mcore optimizers

- .github/workflows/_build_container.yml
- .github/workflows/cicd-main.yml
> ci: Update runner labels

- .github/workflows/semantic-pull-request.yml
First step for auto-generation of changelogs.
This PR adds a new workflow that validates the title of the PR. There are two checks:
1. Check if prefix matches to conventional commit types: https://github.com/commitizen/conventional-commit-types/blob/master/index.json
2. Check that PR title has at most 80 chars. This is not strictly necessary but leads to a nicer summary. Forces to think about a nice summary. The detailed changelog should go into the squashed commit message's _body_.
This workflow runs every time the PR is changed (feel free to test). This includes changes to its title of course. So manual re-running is not necessary. …
> ci: Validate PR title

- docs/user-guide/dpo.rst
[🤖]: Hi @trias702 👋,<br><br>we've cherry picked #345 into `r0.5.0` for you! 🚀<br><br>Please review and approve this cherry pick by your convenience\!
> Cherry pick `docs: Added note about GBS and jsonl samples to DPO tutorial (345)` into `r0.5.0`

- .github/workflows/_build_container.yml
- .github/workflows/cicd-main.yml
- Dockerfile
> ci: Allow building with merge-commit on forks

- .pre-commit-config.yaml
- nemo_aligner/utils/ppo_utils.py
> ci(fix): Make pre-commit sign so that a rebase isn't required

- .github/workflows/_build_container.yml
- .github/workflows/_run_test.yml
- .github/workflows/cicd-main.yml
- tests/conftest.py
- tests/run_unit.sh
- tests/test_distributed.py
> ci: re-enables unit tests by marking broken tests and require all tests

- docs/user-guide/dpo.rst
- docs/user-guide/draftp.rst
- docs/user-guide/modelalignment.rsts
- docs/user-guide/rlhf.rst
- docs/user-guide/rs.rst
- docs/user-guide/sft.rst
- docs/user-guide/spin.rst
- docs/user-guide/steerlm.rst
- docs/user-guide/steerlm2.rst
- adds an introduction to the aligner docs
- replaces (most) references to llama2 models with llama3 models
- makes some minor fixes and clarifications
```python
```
> docs: 0.5.0 documentation updates

- .github/workflows/cherry-pick-release-commit.yml
> ci: Sign-off cherry pick

- docs/user-guide/dpo.rst
- docs/user-guide/draftp.rst
- docs/user-guide/modelalignment.rsts
- docs/user-guide/rlhf.rst
- docs/user-guide/rs.rst
- docs/user-guide/sft.rst
- docs/user-guide/spin.rst
- docs/user-guide/steerlm.rst
- docs/user-guide/steerlm2.rst
[🤖]: Hi @ashors1 👋,<br><br>we've cherry picked #346 into `r0.5.0` for you! 🚀<br><br>Please review and approve this cherry pick by your convenience\!
> Cherry pick `docs: 0.5.0 documentation updates (346)` into `r0.5.0`

- README.md
- docs/user-guide/sft.rst
Add Quick start with NeMo container to main readme. Fixes script path in SFT doc
- README.md
- sft.rst
> docs: main readme and sft docs

- docs/user-guide/sft.rst
> docs: fix code block rendering

- docs/user-guide/sft.rst
[🤖]: Hi @ashors1 👋,<br><br>we've cherry picked #369 into `r0.5.0` for you! 🚀<br><br>Please review and approve this cherry pick by your convenience\!
> Cherry pick `docs: fix code block rendering (369)` into `r0.5.0`

- tests/test_distributed.py
> fix: resolve distributed test hangs

- nemo_aligner/package_info.py
> chore: Set version to `0.5.0`

- docs/user-guide/cai.rst
- docs/user-guide/dpo.rst
- docs/user-guide/draftp.rst
- docs/user-guide/knowledge-distillation.rst
- docs/user-guide/modelalignment.rsts
- docs/user-guide/rlhf.rst
- docs/user-guide/rs.rst
- docs/user-guide/sft.rst
- docs/user-guide/spin.rst
- docs/user-guide/steerlm.rst
- docs/user-guide/steerlm2.rst
> docs: add a link to NeMo's known issues page

- .github/workflows/cherry-pick-release-commit.yml
> ci: Fix cherry pick workflow

- .github/workflows/build-test-publish-wheel.yml
- setup/requirements.txt
> ci: Build, test, and publish a wheel

- .github/workflows/semantic-pull-request.yml
> ci: Move `semantic-pr` into templates repo

- .github/workflows/release.yaml
> ci: Allow dry-run of release

- CHANGELOG.md
> docs: Fix a typo in changelog regarding packing in SFT

- examples/nlp/data/sft/remove_long_dialogues.py
> feat: add sft preprocessing script

- docs/user-guide/knowledge-distillation.rst
> docs: fix KD doc rendering

- nemo_aligner/models/nlp/gpt/megatron_gpt_dpo_model.py
> fix: fix DPO sequence packing + pipeline parallel

- docs/user-guide/aligner-algo-header.rst
- docs/user-guide/evaluation.rst
- examples/nlp/data/sft/remove_long_dialogues.py
> docs: add eval documentation

- nemo_aligner/models/nlp/gpt/megatron_gpt_knowledge_distillation.py
- nemo_aligner/models/nlp/gpt/megatron_gpt_reinforce_actor.py
> fix: resolve more pytorch lightning import bugs (kd/reinforce)

- nemo_aligner/models/nlp/gpt/megatron_gpt_knowledge_distillation.py
- tests/functional/kd.sh
> fix: bug fix for KD + PP

- CHANGELOG.md
> docs: add more details on CP + SFT support

- docs/user-guide/reinforce.rst
> docs: fix typo PRETRAINED_ACTOR_NEMO_FILE -> ACTOR_NEMO_FILE

- docs/user-guide/dpo.rst
> docs: fix minor typo

- nemo_aligner/package_info.py
> chore: Bump to `0.6.0rc1`

- CHANGELOG.md
- docs/user-guide/aligner-algo-header.rst
- docs/user-guide/evaluation.rst
- examples/nlp/data/sft/remove_long_dialogues.py
- nemo_aligner/models/nlp/gpt/megatron_gpt_knowledge_distillation.py
- tests/functional/kd.sh
> chore: cherry-pick fixes for 0.6.0rc1

- docs/user-guide/reinforce.rst
- docs/user-guide/rlhf.rst
> docs: fix reinforce and ppo to specify mpirun requirement

- .github/workflows/release.yaml
> ci: Bump release workflow

- nemo_aligner/package_info.py
> chore: Bump to `0.6.0rc2`

- docs/user-guide/dpo.rst
- docs/user-guide/reinforce.rst
- docs/user-guide/rlhf.rst
> chore: Cherry-pick docs into `r0.6.0`

- .github/workflows/release.yaml
> ci: Update release.yaml

- nemo_aligner/package_info.py
> chore: Update package_info.py

- nemo_aligner/package_info.py
beep boop [🤖]: Hi @ko3n1g 👋,
we've cherry picked #474 into  for you! 🚀
Please review and approve this cherry pick by your convenience!
> Cherry pick `fix: Generate version number (474)` into `r0.6.0`

- nemo_aligner/package_info.py
> fix: Package version string

- nemo_aligner/package_info.py
> fix: Update package_info.py

- docs/user-guide/index.rst
- docs/user-guide/reinforce.rst
> docs: fix linking of reinforce from index and add it to support table

- docs/user-guide/nemoaligner.rsts
> docs: fix code block for install

- tests/functional/dpo.sh
- tests/functional/kd.sh
- tests/functional/ppo.sh
- tests/functional/reinforce.sh
- tests/functional/rm.sh
- tests/functional/sft.sh
- tests/run_mpi_unit.sh
> fix(25.02): fixes for 25.02 state

- .github/workflows/release-freeze.yml
> ci: fix code freeze

- nemo_aligner/package_info.py
> chore: version bump

- CHANGELOG.md
- examples/nlp/data/dpo/prepare_packed_dpo_dataset.py
- examples/nlp/gpt/train_gpt_dpo.py
- nemo_aligner/algorithms/dpo.py
- nemo_aligner/data/nlp/datasets.py
- nemo_aligner/data/nlp/tests/datasets_test.py
- nemo_aligner/models/nlp/gpt/megatron_gpt_dpo_model.py
- tests/functional/dpo.sh
- tests/functional/test_cases/dpo-llama3
- tests/functional/test_cases/dpo-llama3-pack
> feat: add context parallel support for DPO

- nemo_aligner/package_info.py
> chore: update package info for 0.7.0

- .github/workflows/release-freeze.yml
> ci: Add code-freeze dry-run

- CHANGELOG.md
- nemo_aligner/utils/train_utils.py
- nemo_aligner/utils/utils.py
> fix: Fixes for mcore distributed optimizer

- .github/workflows/cherry-pick-release-commit.yml
> ci: Cherry-pick from `dev`

- CHANGELOG.md
- nemo_aligner/utils/train_utils.py
- nemo_aligner/utils/utils.py
> fix(cherry-pick): Fixes for mcore distributed optimizer (#512)

- .github/workflows/build-test-publish-wheel.yml
- .github/workflows/release-freeze.yml
- .github/workflows/release.yaml
- nemo_aligner/__init__.py
- setup/requirements.txt
> ci: update workflows (#514)

- .github/workflows/cicd-main.yml
> ci: Bump build workflow

- .github/workflows/cicd-main.yml
- CHANGELOG.md
> docs: add documentation for EP and uncomment EP test

- docs/user-guide/sft.rst
> docs: Fix broken sequence packing hyperlinks

- docs/user-guide/general.rst
- docs/user-guide/index.rst
> docs: Add FP8 documentation

- README.md
- docs/user-guide/nemoaligner.rsts
> docs: fix container pointer to 24.12

- CHANGELOG.md
> docs:  Add changelog for 0.7.0

- CHANGELOG.md
> docs:  Add changelog for 0.7.0 (#530)

- nemo_aligner/package_info.py
> chore: Release 0.7.0

- nemo_aligner/package_info.py
> chore: Bump to 0.7.1

- .github/workflows/cicd-main.yml
Disable changed-files github action
- Disable changed-files github action
```python
```
> ci: Disable changed-files github action
